# logfilename                   [owner:group]  mode  count  size  when  flags
/var/log/devicelocker.log       root:wheel     640   7      1024  *     NZ
/var/log/devicelocker.err       root:wheel     640   7      1024  *     NZ
